### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by tendres** [PeterAustinMoore/Socrata#3]
Using the latest dev version (2.15.0-Master) on OS X - ran into this after QGIS was open for a while. Initial attempts to open were successful.

File "/Users/tendres/.qgis2/python/plugins/Socrata/Socrata.py", line 321, in run
			    result = self.run()
			RuntimeError: maximum recursion depth exceeded

**Comment by PeterAustinMoore** [comment]
Should be fixed in version 0.2 which was pushed today.
