### ISSUE TITLE
Invalid layers on data.detroitmi.gov

### ISSUE THREAD

**Issue by nickballen** [PeterAustinMoore/Socrata#6]
I’m having trouble calling new layers into the QGIS application--not sure whether it's particular to my Socrata instance or a plugin bug. When I attempt to download any file from [Detroit Open Data Portal](http://data.detroitmi.gov), I get this error message:

> The layer https://data.detroitmi.gov/api/geospatial/fxkw-udwf?method=export&format=geojson is not a valid layer and can not be added to the map

This is true for all layers I attempt to load. I'm on QGIS 2.7 on a Windows 10 machine.

**Comment by PeterAustinMoore** [comment]
hi @nickballen this might be related to the TLS issue #5 - which appears to be resolved for mac but not for Windows versions ([related documentation on a way to resolve it](http://semiautomaticclassificationmanual-v5.readthedocs.io/en/latest/faq.html#error-56-ssl-connection-error-unable-to-download-sentinel-2-images-why)) 

A way to test it would be to try and [import the layer](https://gis.stackexchange.com/questions/17035/how-to-display-geojson-from-an-url-in-a-layer) using that url and see if it succeeds or fails.

My thought is with QGIS3 right around the corner, it will be resolved with that update and if not I will try and figure out a different strategy, but any ideas would be welcomed!

**Comment by PeterAustinMoore** [comment]
hey @nickballen - version 2 of this plugin has been released for QGIS3 and has resolved the underlying SSL issue. So I am going to close this out.
